import { BaseballStatCategory } from './baseball-stat-category.model';
import { BaseballStatType } from './baseball-stat-type.model';

export const MLB_STATS_MAP = {
  0: { abbrev: 'AB', description: 'At Bats', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  1: { abbrev: 'H', description: 'Hits', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  2: { abbrev: 'AVG', description: 'Batting Average', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  3: { abbrev: '2B', description: 'Doubles', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  4: { abbrev: '3B', description: 'Triples', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  5: { abbrev: 'HR', description: 'Home Runs', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  6: { abbrev: 'XBH', description: 'Extra Base Hits', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  7: { abbrev: '1B', description: 'Singles', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  8: { abbrev: 'TB', description: 'Total Bases', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  9: { abbrev: 'SLG', description: 'Slugging Pct', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  10: { abbrev: 'BB', description: 'Walks', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  11: {
    abbrev: 'IBB',
    description: 'Intentional Walks',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  12: { abbrev: 'HBP', description: 'Hit by Pitch', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  13: { abbrev: 'SF', description: 'Sacrifice Flies', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  14: { abbrev: 'SH', description: 'Sacrifice Hits', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  15: { abbrev: 'SAC', description: 'Sacrifices', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  16: {
    abbrev: 'PA',
    description: 'Plate Appearances',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  17: { abbrev: 'OBP', description: 'On Base Pct', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  18: {
    abbrev: 'OPS',
    description: 'On Base plus Slugging Pct',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  19: { abbrev: 'RC', description: 'Runs Created', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  20: { abbrev: 'R', description: 'Runs Scored', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  21: { abbrev: 'RBI', description: 'Runs Batted In', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  22: {
    abbrev: 'GWRBI',
    description: 'Game Winning RBI',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  23: { abbrev: 'SB', description: 'Stolen Bases', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  24: { abbrev: 'CS', description: 'Caught Stealing', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  25: {
    abbrev: 'SBN',
    description: 'Net Stolen Bases',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  26: {
    abbrev: 'GIDP',
    description: 'Ground into Double Plays',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  27: { abbrev: 'KO', description: 'Strikeouts', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  28: { abbrev: 'TP', description: 'Total Pitches', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  29: {
    abbrev: 'PPA',
    description: 'Pitches per Plate Appearance',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  30: {
    abbrev: 'CYC',
    description: 'Hitting for the Cycle',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  31: {
    abbrev: 'GSHR',
    description: 'Grand Slam Home Runs',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  32: { abbrev: 'APP', description: 'Appearances', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  33: { abbrev: 'GS', description: 'Games Started', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  34: {
    abbrev: 'IP',
    description: 'Innings Pitched',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  35: { abbrev: 'BF', description: 'Batters Faced', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  36: { abbrev: 'PC', description: 'Pitch Count', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  37: { abbrev: 'HA', description: 'Hits Allowed', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  38: {
    abbrev: 'BAA',
    description: 'Batting Average Against',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  39: { abbrev: 'BBI', description: 'Walks Issued', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  40: {
    abbrev: 'IBBI',
    description: 'Intentional Walks',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  41: {
    abbrev: 'WHIP',
    description: 'Walks plus Hits Per Innings Pitched',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  42: { abbrev: 'HB', description: 'Hit Batsmen', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  43: {
    abbrev: 'OBA',
    description: 'On Base Pct Against',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  44: { abbrev: 'RA', description: 'Runs Allowed', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  45: { abbrev: 'ER', description: 'Earned Runs', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  46: {
    abbrev: 'HRA',
    description: 'Home Runs Allowed',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  47: {
    abbrev: 'ERA',
    description: 'Earned Run Average',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  48: { abbrev: 'K', description: 'Strikeouts', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  49: {
    abbrev: 'K/9',
    description: 'Strikeouts per 9 Innings',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  50: { abbrev: 'WP', description: 'Wild Pitches', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  51: { abbrev: 'B', description: 'Balks', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  52: { abbrev: 'PKO', description: 'Pick Offs', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  53: { abbrev: 'W', description: 'Wins', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  54: { abbrev: 'L', description: 'Losses', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  55: { abbrev: 'WIN%', description: 'Win Pct', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  56: {
    abbrev: 'SOP',
    description: 'Save Opportunities',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  57: { abbrev: 'SV', description: 'Saves', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  58: { abbrev: 'BS', description: 'Blown Saves', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  59: { abbrev: 'SV%', description: 'Save Pct', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  60: { abbrev: 'HD', description: 'Holds', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  61: {
    abbrev: 'IRS',
    description: 'Inherited Runners Scored',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  62: { abbrev: 'CG', description: 'Complete Games', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  63: { abbrev: 'QS', description: 'Quality Starts', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  64: { abbrev: 'SO', description: 'Shutouts', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  65: { abbrev: 'NH', description: 'No Hitters', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  66: { abbrev: 'PG', description: 'Perfect Games', statCategoryId: BaseballStatCategory.Pitching, statTypeId: BaseballStatType.Pitching },
  67: { abbrev: 'FC', description: 'Fielding Chances', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Defense },
  68: { abbrev: 'PO', description: 'Put Outs', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Defense },
  69: { abbrev: 'AST', description: 'Assists', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Defense },
  70: {
    abbrev: 'OFAST',
    description: 'Outfield Assists',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Defense,
  },
  71: { abbrev: 'FPCT', description: 'Fielding Pct', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Defense },
  72: { abbrev: 'E', description: 'Errors', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Defense },
  73: {
    abbrev: 'DPT',
    description: 'Double Plays Turned',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Defense,
  },
  74: { abbrev: 'BTW', description: 'Batter Team Win', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  75: {
    abbrev: 'BTL',
    description: 'Batter Team Loss',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  76: {
    abbrev: 'PTW',
    description: 'Pitcher Team Win',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  77: {
    abbrev: 'PTL',
    description: 'Pitcher Team Loss',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  78: {
    abbrev: 'SFA',
    description: 'Sacrifice Flies Allowed',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  79: {
    abbrev: 'SHA',
    description: 'Sacrifice Hits Allowed',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  80: {
    abbrev: 'CIA',
    description: 'Catcher Interference Allowed',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  81: { abbrev: 'GP', description: 'Games Played', statCategoryId: BaseballStatCategory.Batting, statTypeId: BaseballStatType.Batting },
  82: {
    abbrev: 'K/BB',
    description: 'Strikeout to Walk Ratio',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  83: {
    abbrev: 'SVHD',
    description: 'Saves Plus Holds',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  84: {
    abbrev: 'PBS',
    description: 'Probable Start',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  100: {
    abbrev: 'FIP',
    description: 'Fielding Independent Pitching (FIP)',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  101: {
    abbrev: 'wOBA',
    description: 'Weighted On-Base Average (wOBA)',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  102: {
    abbrev: 'wRAA',
    description: 'Weighted Runs Above Average (wRAA)',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  103: {
    abbrev: 'BABIP',
    description: 'Batting Average on Balls In Play (BABIP)',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  104: {
    abbrev: 'ISO',
    description: 'Isolated Power',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
  105: {
    abbrev: 'LOB%',
    description: 'Left On Base %',
    statCategoryId: BaseballStatCategory.Pitching,
    statTypeId: BaseballStatType.Pitching,
  },
  106: {
    abbrev: 'wRC',
    description: 'Weighted Runs Created',
    statCategoryId: BaseballStatCategory.Batting,
    statTypeId: BaseballStatType.Batting,
  },
} as const;

export const MLB_STATS_LIST = Object.entries(MLB_STATS_MAP).map(([key, stat]) => {
  return {
    ...stat,
    id: key,
  };
});
export const MLB_STATS_KEYS = Object.keys(MLB_STATS_MAP);

export const BATTER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === BaseballStatType.Batting);
export const BATTER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === BaseballStatCategory.Batting);
export const BATTER_STATS_LIST_OPTIONS = BATTER_STATS_LIST.map(p => ({ label: p.description, value: p.id }));

export const PITCHER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === BaseballStatType.Pitching);
export const PITCHER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === BaseballStatCategory.Pitching);

export const DEFENSE_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === BaseballStatType.Defense);
