import { NflTeam } from './nfl-team.model';

export const NFL_TEAM_MAP = {
  [NflTeam.Bye]: 'Bye',
  [NflTeam.FA]: 'FA',
  [NflTeam.ATL]: 'ATL',
  [NflTeam.BUF]: 'BUF',
  [NflTeam.CHI]: 'CHI',
  [NflTeam.CIN]: 'CIN',
  [NflTeam.CLE]: 'CLE',
  [NflTeam.DAL]: 'DAL',
  [NflTeam.DEN]: 'DEN',
  [NflTeam.DET]: 'DET',
  [NflTeam.GB]: 'GB',
  [NflTeam.TEN]: 'TEN',
  [NflTeam.IND]: 'IND',
  [NflTeam.KC]: 'KC',
  [NflTeam.OAK]: 'OAK',
  [NflTeam.LAR]: 'LAR',
  [NflTeam.MIA]: 'MIA',
  [NflTeam.MIN]: 'MIN',
  [NflTeam.NE]: 'NE',
  [NflTeam.NO]: 'NO',
  [NflTeam.NYG]: 'NYG',
  [NflTeam.NYJ]: 'NYJ',
  [NflTeam.PHI]: 'PHI',
  [NflTeam.ARI]: 'ARI',
  [NflTeam.PIT]: 'PIT',
  [NflTeam.LAC]: 'LAC',
  [NflTeam.SF]: 'SF',
  [NflTeam.SEA]: 'SEA',
  [NflTeam.TB]: 'TB',
  [NflTeam.WSH]: 'WSH',
  [NflTeam.CAR]: 'CAR',
  [NflTeam.JAX]: 'JAX',
  [NflTeam.BAL]: 'BAL',
  [NflTeam.HOU]: 'HOU',
} as const;
