import { MOCK_CLIENT_GRIDIRON_PLAYER } from '@sports-ui/daily-fantasy-sdk/daily-fantasy-client/mocks';
import { GridIronPlayer } from './nfl-gridIron.model';

export const MOCK_GRIDIRON_PLAYER: GridIronPlayer = {
  opp: MOCK_CLIENT_GRIDIRON_PLAYER.OPP,
  pos: MOCK_CLIENT_GRIDIRON_PLAYER.POS,
  team: MOCK_CLIENT_GRIDIRON_PLAYER.TEAM,
  slate: MOCK_CLIENT_GRIDIRON_PLAYER.SLATE,
  injury: MOCK_CLIENT_GRIDIRON_PLAYER.INJURY,
  player: MOCK_CLIENT_GRIDIRON_PLAYER.PLAYER,
  playerId: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PLAYERID),
  salary: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SALARY),
  scheduleId: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SCHEDULE_ID),
  paatt: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PAATT),
  comp: Number(MOCK_CLIENT_GRIDIRON_PLAYER.CMP),
  payds: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PAYDS),
  patd: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PATD),
  int: Number(MOCK_CLIENT_GRIDIRON_PLAYER.INT),
  ruatt: Number(MOCK_CLIENT_GRIDIRON_PLAYER.RUATT),
  ruyds: Number(MOCK_CLIENT_GRIDIRON_PLAYER.RUYDS),
  rutd: Number(MOCK_CLIENT_GRIDIRON_PLAYER.RUTD),
  tar: Number(MOCK_CLIENT_GRIDIRON_PLAYER.TAR),
  rec: Number(MOCK_CLIENT_GRIDIRON_PLAYER.REC),
  reyds: Number(MOCK_CLIENT_GRIDIRON_PLAYER.REYDS),
  retd: Number(MOCK_CLIENT_GRIDIRON_PLAYER.RETD),
  fpts: Number(MOCK_CLIENT_GRIDIRON_PLAYER.FPTS),
  sdFpts: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SDFPTS),
  fptsPerDollar: Number(MOCK_CLIENT_GRIDIRON_PLAYER['FPTS/$']),
  floor: Number(MOCK_CLIENT_GRIDIRON_PLAYER.FLOOR),
  sdFloor: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SDFLOOR),
  ceil: Number(MOCK_CLIENT_GRIDIRON_PLAYER.CEIL),
  sdCeil: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SDCEIL),
  smash: Number(MOCK_CLIENT_GRIDIRON_PLAYER.SMASH),
  value: Number(MOCK_CLIENT_GRIDIRON_PLAYER.VALUE),
  pown: Number(MOCK_CLIENT_GRIDIRON_PLAYER.POWN),
  partnerId: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PARTNERID),
  ownership: {
    [93936]: Number(MOCK_CLIENT_GRIDIRON_PLAYER.OWNERSHIP['93936']),
  },
  rgid: Number(MOCK_CLIENT_GRIDIRON_PLAYER.RGID),
};

export const MOCK_GRIDIRON_PLAYER_NULL: GridIronPlayer = {
  opp: null,
  pos: null,
  team: null,
  slate: null,
  injury: null,
  player: null,
  playerId: Number(MOCK_CLIENT_GRIDIRON_PLAYER.PLAYERID),
  salary: null,
  scheduleId: null,
  paatt: null,
  comp: null,
  payds: null,
  patd: null,
  int: null,
  ruatt: null,
  ruyds: null,
  rutd: null,
  tar: null,
  rec: null,
  reyds: null,
  retd: null,
  fpts: null,
  sdFpts: null,
  fptsPerDollar: null,
  floor: null,
  sdFloor: null,
  ceil: null,
  sdCeil: null,
  smash: null,
  value: null,
  pown: null,
  partnerId: null,
  ownership: {},
  rgid: null,
};
