export const environment = {
  production: false,
  tomorrowIO: '',
  awsBase: '',
  dfsSource: '',
  dailyFantasyBase: '',
  dailyFantasyJsonBase: '',
  espnBase: '',
  espnBaseApi: '',
  espnFantasyBaseV3: '',
  espnFastcastServiceUri: '',
  espnFastcastBase: '',
  espnWebsocketHost: '',
  espnOneFeed: '',
  espncdn: '',
  espnCommon: '',
  espnWatson: '',
  kambicdnBase: '',
  sportsApi: '',
  supaUrl: '',
  supaKey: '',
};
