import { enumAsList } from '@app/@shared/helpers/enum-as-list';
import { Lineup } from '../models/lineup.model';
import { MLB_POSITION } from './position.const';

export enum MLB_LINEUP {
  C,
  '1B',
  '2B',
  '3B',
  SS,
  OF,
  '2B/SS',
  '1B/3B',
  LF,
  CF,
  RF,
  DH,
  UTIL,
  P,
  SP,
  RP,
  BE,
  IL,
  INV,
  IF,
  B,
  P2,
  MISC,
}

export const PITCHING_LINEUP_SLOTS = [MLB_LINEUP.P, MLB_LINEUP.SP, MLB_LINEUP.RP, MLB_LINEUP.P2];

export const mlbLineupList = enumAsList(MLB_LINEUP);

export const MLB_LINEUP_MAP: Record<number, Lineup> = {
  0: {
    parentId: 12,
    abbrev: 'C',
    bench: false,
    eligiblePositions: [MLB_POSITION.C],
    lineupSlotEligible: true,
    name: 'Catcher',
    starter: true,
  },
  1: {
    parentId: 7,
    abbrev: '1B',
    bench: false,
    eligiblePositions: [MLB_POSITION['1B']],
    lineupSlotEligible: true,
    name: 'First Base',
    starter: true,
  },
  2: { parentId: 6, abbrev: '2B', bench: false, eligiblePositions: [4], lineupSlotEligible: true, name: 'Second Base', starter: true },
  3: { parentId: 7, abbrev: '3B', bench: false, eligiblePositions: [5], lineupSlotEligible: true, name: 'Third Base', starter: true },
  4: { parentId: 6, abbrev: 'SS', bench: false, eligiblePositions: [6], lineupSlotEligible: true, name: 'Shortstop', starter: true },
  5: { parentId: 12, abbrev: 'OF', bench: false, eligiblePositions: [7, 8, 9], lineupSlotEligible: true, name: 'Outfield', starter: true },
  6: {
    parentId: 12,
    abbrev: '2B/SS',
    bench: false,
    eligiblePositions: [4, 6],
    lineupSlotEligible: true,
    name: 'Middle Infielder',
    starter: true,
  },
  7: {
    parentId: 12,
    abbrev: '1B/3B',
    bench: false,
    eligiblePositions: [MLB_POSITION['1B'], 5],
    lineupSlotEligible: true,
    name: 'Corner Infielder',
    starter: true,
  },
  8: { parentId: 5, abbrev: 'LF', bench: false, eligiblePositions: [7], lineupSlotEligible: true, name: 'Left Field', starter: true },
  9: { parentId: 5, abbrev: 'CF', bench: false, eligiblePositions: [8], lineupSlotEligible: true, name: 'Center Field', starter: true },
  10: { parentId: 5, abbrev: 'RF', bench: false, eligiblePositions: [9], lineupSlotEligible: true, name: 'Right Field', starter: true },
  11: {
    parentId: 12,
    abbrev: 'DH',
    bench: false,
    eligiblePositions: [10],
    lineupSlotEligible: true,
    name: 'Designated Hitter',
    starter: true,
  },
  12: {
    parentId: 21,
    abbrev: 'UTIL',
    bench: false,
    eligiblePositions: [MLB_POSITION.C, MLB_POSITION['1B'], 4, 5, 6, 7, 8, 9, 10],
    lineupSlotEligible: true,
    name: 'Utility',
    starter: true,
  },
  13: { parentId: 22, abbrev: 'P', bench: false, eligiblePositions: [1, 11], lineupSlotEligible: true, name: 'Pitcher', starter: true },
  14: {
    parentId: 13,
    abbrev: 'SP',
    bench: false,
    eligiblePositions: [1],
    lineupSlotEligible: true,
    name: 'Starting Pitcher',
    starter: true,
  },
  15: {
    parentId: 13,
    abbrev: 'RP',
    bench: false,
    eligiblePositions: [11],
    lineupSlotEligible: true,
    name: 'Relief Pitcher',
    starter: true,
  },
  16: {
    parentId: 23,
    abbrev: 'BE',
    bench: true,
    eligiblePositions: [1, MLB_POSITION.C, MLB_POSITION['1B'], 4, 5, 6, 7, 8, 9, 10, 11],
    lineupSlotEligible: true,
    name: 'Bench',
    starter: false,
  },
  17: {
    parentId: 23,
    abbrev: 'IL',
    bench: false,
    eligiblePositions: [1, MLB_POSITION.C, MLB_POSITION['1B'], 4, 5, 6, 7, 8, 9, 10, 11],
    lineupSlotEligible: true,
    name: 'Injured List',
    starter: false,
  },
  18: {
    parentId: 23,
    abbrev: 'INV',
    bench: false,
    eligiblePositions: [],
    lineupSlotEligible: false,
    name: 'Invalid Player',
    starter: false,
  },
  19: {
    parentId: 12,
    abbrev: 'IF',
    bench: false,
    eligiblePositions: [MLB_POSITION['1B'], 4, 5, 6],
    lineupSlotEligible: true,
    name: 'Infielder',
    starter: true,
  },
  20: {
    parentId: 21,
    abbrev: 'B',
    bench: false,
    eligiblePositions: [MLB_POSITION.C, MLB_POSITION['1B'], 4, 5, 6, 7, 8, 9, 10],
    lineupSlotEligible: false,
    name: 'Batters',
    starter: false,
  },
  21: { parentId: 22, abbrev: 'P', bench: false, eligiblePositions: [1, 11], lineupSlotEligible: false, name: 'Pitchers', starter: false },
  22: {
    parentId: 23,
    abbrev: 'MISC',
    bench: false,
    eligiblePositions: [],
    lineupSlotEligible: false,
    name: 'Miscellaneous',
    starter: false,
  },
};

export const MLB_LINEUP_LIST = Object.values(MLB_LINEUP_MAP);
export const MLB_LINEUP_STARTERS = MLB_LINEUP_LIST.filter(p => p.starter);
export const MLB_LINEUP_BENCH = MLB_LINEUP_LIST.filter(p => p.bench);

export const PitcherIdSet: Set<MLB_LINEUP> = new Set([MLB_LINEUP.P, MLB_LINEUP.SP, MLB_LINEUP.RP, MLB_LINEUP.P2]);
