import { StatCategory, StatsMap, StatType } from '../models/mlb-stats.model';

export const MLB_STATS_MAP: StatsMap = {
  '0': { abbrev: 'AB', description: 'At Bats', statCategoryId: 1, statTypeId: 1 },
  '1': { abbrev: 'H', description: 'Hits', statCategoryId: 1, statTypeId: 1 },
  '2': { abbrev: 'AVG', description: 'Batting Average', statCategoryId: 1, statTypeId: 1 },
  '3': { abbrev: '2B', description: 'Doubles', statCategoryId: 1, statTypeId: 1 },
  '4': { abbrev: '3B', description: 'Triples', statCategoryId: 1, statTypeId: 1 },
  '5': { abbrev: 'HR', description: 'Home Runs', statCategoryId: 1, statTypeId: 1 },
  '6': { abbrev: 'XBH', description: 'Extra Base Hits', statCategoryId: 1, statTypeId: 1 },
  '7': { abbrev: '1B', description: 'Singles', statCategoryId: 1, statTypeId: 1 },
  '8': { abbrev: 'TB', description: 'Total Bases', statCategoryId: 1, statTypeId: 1 },
  '9': { abbrev: 'SLG', description: 'Slugging Pct', statCategoryId: 1, statTypeId: 1 },
  '10': { abbrev: 'BB', description: 'Walks', statCategoryId: 1, statTypeId: 1 },
  '11': { abbrev: 'IBB', description: 'Intentional Walks', statCategoryId: 1, statTypeId: 1 },
  '12': { abbrev: 'HBP', description: 'Hit by Pitch', statCategoryId: 1, statTypeId: 1 },
  '13': { abbrev: 'SF', description: 'Sacrifice Flies', statCategoryId: 1, statTypeId: 1 },
  '14': { abbrev: 'SH', description: 'Sacrifice Hits', statCategoryId: 1, statTypeId: 1 },
  '15': { abbrev: 'SAC', description: 'Sacrifices', statCategoryId: 1, statTypeId: 1 },
  '16': { abbrev: 'PA', description: 'Plate Appearances', statCategoryId: 1, statTypeId: 1 },
  '17': { abbrev: 'OBP', description: 'On Base Pct', statCategoryId: 1, statTypeId: 1 },
  '18': { abbrev: 'OPS', description: 'On Base plus Slugging Pct', statCategoryId: 1, statTypeId: 1 },
  '19': { abbrev: 'RC', description: 'Runs Created', statCategoryId: 1, statTypeId: 1 },
  '20': { abbrev: 'R', description: 'Runs Scored', statCategoryId: 1, statTypeId: 1 },
  '21': { abbrev: 'RBI', description: 'Runs Batted In', statCategoryId: 1, statTypeId: 1 },
  '22': { abbrev: 'GWRBI', description: 'Game Winning RBI', statCategoryId: 1, statTypeId: 1 },
  '23': { abbrev: 'SB', description: 'Stolen Bases', statCategoryId: 1, statTypeId: 1 },
  '24': { abbrev: 'CS', description: 'Caught Stealing', statCategoryId: 1, statTypeId: 1 },
  '25': { abbrev: 'SBN', description: 'Net Stolen Bases', statCategoryId: 1, statTypeId: 1 },
  '26': { abbrev: 'GIDP', description: 'Ground into Double Plays', statCategoryId: 1, statTypeId: 1 },
  '27': { abbrev: 'KO', description: 'Strikeouts', statCategoryId: 1, statTypeId: 1 },
  '28': { abbrev: 'TP', description: 'Total Pitches', statCategoryId: 1, statTypeId: 1 },
  '29': { abbrev: 'PPA', description: 'Pitches per Plate Appearance', statCategoryId: 1, statTypeId: 1 },
  '30': { abbrev: 'CYC', description: 'Hitting for the Cycle', statCategoryId: 1, statTypeId: 1 },
  '31': { abbrev: 'GSHR', description: 'Grand Slam Home Runs', statCategoryId: 1, statTypeId: 1 },
  '32': { abbrev: 'APP', description: 'Appearances', statCategoryId: 2, statTypeId: 2 },
  '33': { abbrev: 'GS', description: 'Games Started', statCategoryId: 2, statTypeId: 2 },
  '34': { abbrev: 'IP', description: 'Innings Pitched', statCategoryId: 2, statTypeId: 2 },
  '35': { abbrev: 'BF', description: 'Batters Faced', statCategoryId: 2, statTypeId: 2 },
  '36': { abbrev: 'PC', description: 'Pitch Count', statCategoryId: 2, statTypeId: 2 },
  '37': { abbrev: 'HA', description: 'Hits Allowed', statCategoryId: 2, statTypeId: 2 },
  '38': { abbrev: 'BAA', description: 'Batting Average Against', statCategoryId: 2, statTypeId: 2 },
  '39': { abbrev: 'BBI', description: 'Walks Issued', statCategoryId: 2, statTypeId: 2 },
  '40': { abbrev: 'IBBI', description: 'Intentional Walks', statCategoryId: 2, statTypeId: 2 },
  '41': { abbrev: 'WHIP', description: 'Walks plus Hits Per Innings Pitched', statCategoryId: 2, statTypeId: 2 },
  '42': { abbrev: 'HB', description: 'Hit Batsmen', statCategoryId: 2, statTypeId: 2 },
  '43': { abbrev: 'OBA', description: 'On Base Pct Against', statCategoryId: 2, statTypeId: 2 },
  '44': { abbrev: 'RA', description: 'Runs Allowed', statCategoryId: 2, statTypeId: 2 },
  '45': { abbrev: 'ER', description: 'Earned Runs', statCategoryId: 2, statTypeId: 2 },
  '46': { abbrev: 'HRA', description: 'Home Runs Allowed', statCategoryId: 2, statTypeId: 2 },
  '47': { abbrev: 'ERA', description: 'Earned Run Average', statCategoryId: 2, statTypeId: 2 },
  '48': { abbrev: 'K', description: 'Strikeouts', statCategoryId: 2, statTypeId: 2 },
  '49': { abbrev: 'K/9', description: 'Strikeouts per 9 Innings', statCategoryId: 2, statTypeId: 2 },
  '50': { abbrev: 'WP', description: 'Wild Pitches', statCategoryId: 2, statTypeId: 2 },
  '51': { abbrev: 'B', description: 'Balks', statCategoryId: 2, statTypeId: 2 },
  '52': { abbrev: 'PKO', description: 'Pick Offs', statCategoryId: 2, statTypeId: 2 },
  '53': { abbrev: 'W', description: 'Wins', statCategoryId: 2, statTypeId: 2 },
  '54': { abbrev: 'L', description: 'Losses', statCategoryId: 2, statTypeId: 2 },
  '55': { abbrev: 'WIN%', description: 'Win Pct', statCategoryId: 2, statTypeId: 2 },
  '56': { abbrev: 'SOP', description: 'Save Opportunities', statCategoryId: 2, statTypeId: 2 },
  '57': { abbrev: 'SV', description: 'Saves', statCategoryId: 2, statTypeId: 2 },
  '58': { abbrev: 'BS', description: 'Blown Saves', statCategoryId: 2, statTypeId: 2 },
  '59': { abbrev: 'SV%', description: 'Save Pct', statCategoryId: 2, statTypeId: 2 },
  '60': { abbrev: 'HD', description: 'Holds', statCategoryId: 2, statTypeId: 2 },
  '61': { abbrev: 'IRS', description: 'Inherited Runners Scored', statCategoryId: 2, statTypeId: 2 },
  '62': { abbrev: 'CG', description: 'Complete Games', statCategoryId: 2, statTypeId: 2 },
  '63': { abbrev: 'QS', description: 'Quality Starts', statCategoryId: 2, statTypeId: 2 },
  '64': { abbrev: 'SO', description: 'Shutouts', statCategoryId: 2, statTypeId: 2 },
  '65': { abbrev: 'NH', description: 'No Hitters', statCategoryId: 2, statTypeId: 2 },
  '66': { abbrev: 'PG', description: 'Perfect Games', statCategoryId: 2, statTypeId: 2 },
  '67': { abbrev: 'FC', description: 'Fielding Chances', statCategoryId: 1, statTypeId: 3 },
  '68': { abbrev: 'PO', description: 'Put Outs', statCategoryId: 1, statTypeId: 3 },
  '69': { abbrev: 'AST', description: 'Assists', statCategoryId: 1, statTypeId: 3 },
  '70': { abbrev: 'OFAST', description: 'Outfield Assists', statCategoryId: 1, statTypeId: 3 },
  '71': { abbrev: 'FPCT', description: 'Fielding Pct', statCategoryId: 1, statTypeId: 3 },
  '72': { abbrev: 'E', description: 'Errors', statCategoryId: 1, statTypeId: 3 },
  '73': { abbrev: 'DPT', description: 'Double Plays Turned', statCategoryId: 1, statTypeId: 3 },
  '74': { abbrev: 'BTW', description: 'Batter Team Win', statCategoryId: 1, statTypeId: 1 },
  '75': { abbrev: 'BTL', description: 'Batter Team Loss', statCategoryId: 1, statTypeId: 1 },
  '76': { abbrev: 'PTW', description: 'Pitcher Team Win', statCategoryId: 2, statTypeId: 2 },
  '77': { abbrev: 'PTL', description: 'Pitcher Team Loss', statCategoryId: 2, statTypeId: 2 },
  '78': { abbrev: 'SFA', description: 'Sacrifice Flies Allowed', statCategoryId: 2, statTypeId: 2 },
  '79': { abbrev: 'SHA', description: 'Sacrifice Hits Allowed', statCategoryId: 2, statTypeId: 2 },
  '80': { abbrev: 'CIA', description: 'Catcher Interference Allowed', statCategoryId: 2, statTypeId: 2 },
  '81': { abbrev: 'GP', description: 'Games Played', statCategoryId: 1, statTypeId: 1 },
  '82': { abbrev: 'K/BB', description: 'Strikeout to Walk Ratio', statCategoryId: 2, statTypeId: 2 },
  '83': { abbrev: 'SVHD', description: 'Saves Plus Holds', statCategoryId: 2, statTypeId: 2 },
  '84': { abbrev: 'PBS', description: 'Probable Start', statCategoryId: 2, statTypeId: 2 },
};

export const MLB_STATS_LIST = Object.values(MLB_STATS_MAP);

export const BATTER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === StatType.Batting);
export const BATTER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === StatCategory.Batting);

export const PITCHER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === StatType.Pitching);
export const PITCHER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === StatCategory.Pitching);

export const DEFENSE_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === StatType.Defense);
