export enum MLB_TEAM {
  FA,
  Bal,
  Bos,
  LAA,
  ChW,
  Cle,
  Det,
  KC,
  Mil,
  Min,
  NYY,
  Oak,
  Sea,
  Tex,
  Tor,
  Atl,
  ChC,
  Cin,
  Hou,
  LAD,
  Wsh,
  NYM,
  Phi,
  Pit,
  StL,
  SD,
  SF,
  Col,
  Mia,
  Ari,
  TB,
}

export const MLB_TEAM_MAP: { [key in MLB_TEAM]: string } = {
  [MLB_TEAM.FA]: 'FA',
  [MLB_TEAM.Bal]: 'Bal',
  [MLB_TEAM.Bos]: 'Bos',
  [MLB_TEAM.LAA]: 'LAA',
  [MLB_TEAM.ChW]: 'ChW',
  [MLB_TEAM.Cle]: 'Cle',
  [MLB_TEAM.Det]: 'Det',
  [MLB_TEAM.KC]: 'KC',
  [MLB_TEAM.Mil]: 'Mil',
  [MLB_TEAM.Min]: 'Min',
  [MLB_TEAM.NYY]: 'NYY',
  [MLB_TEAM.Oak]: 'Oak',
  [MLB_TEAM.Sea]: 'Sea',
  [MLB_TEAM.Tex]: 'Tex',
  [MLB_TEAM.Tor]: 'Tor',
  [MLB_TEAM.Atl]: 'Atl',
  [MLB_TEAM.ChC]: 'ChC',
  [MLB_TEAM.Cin]: 'Cin',
  [MLB_TEAM.Hou]: 'Hou',
  [MLB_TEAM.LAD]: 'LAD',
  [MLB_TEAM.Wsh]: 'Wsh',
  [MLB_TEAM.NYM]: 'NYM',
  [MLB_TEAM.Phi]: 'Phi',
  [MLB_TEAM.Pit]: 'Pit',
  [MLB_TEAM.StL]: 'StL',
  [MLB_TEAM.SD]: 'SD',
  [MLB_TEAM.SF]: 'SF',
  [MLB_TEAM.Col]: 'Col',
  [MLB_TEAM.Mia]: 'Mia',
  [MLB_TEAM.Ari]: 'Ari',
  [MLB_TEAM.TB]: 'TB',
};
