export namespace MlbTeam {
  export enum Team {
    FA,
    Bal,
    Bos,
    LAA,
    ChW,
    Cle,
    Det,
    KC,
    Mil,
    Min,
    NYY,
    Oak,
    Sea,
    Tex,
    Tor,
    Atl,
    ChC,
    Cin,
    Hou,
    LAD,
    Wsh,
    NYM,
    Phi,
    Pit,
    StL,
    SD,
    SF,
    Col,
    Mia,
    Ari,
    TB,
  }

  export const Map: { [key in Team]: string } = {
    [Team.FA]: 'FA',
    [Team.Bal]: 'Bal',
    [Team.Bos]: 'Bos',
    [Team.LAA]: 'LAA',
    [Team.ChW]: 'ChW',
    [Team.Cle]: 'Cle',
    [Team.Det]: 'Det',
    [Team.KC]: 'KC',
    [Team.Mil]: 'Mil',
    [Team.Min]: 'Min',
    [Team.NYY]: 'NYY',
    [Team.Oak]: 'Oak',
    [Team.Sea]: 'Sea',
    [Team.Tex]: 'Tex',
    [Team.Tor]: 'Tor',
    [Team.Atl]: 'Atl',
    [Team.ChC]: 'ChC',
    [Team.Cin]: 'Cin',
    [Team.Hou]: 'Hou',
    [Team.LAD]: 'LAD',
    [Team.Wsh]: 'Wsh',
    [Team.NYM]: 'NYM',
    [Team.Phi]: 'Phi',
    [Team.Pit]: 'Pit',
    [Team.StL]: 'StL',
    [Team.SD]: 'SD',
    [Team.SF]: 'SF',
    [Team.Col]: 'Col',
    [Team.Mia]: 'Mia',
    [Team.Ari]: 'Ari',
    [Team.TB]: 'TB',
  };
}
