import { MlbTeam } from './mlb-team.model';

export const MLB_TEAM_MAP: { [key in MlbTeam]: string } = {
  [MlbTeam.FA]: 'FA',
  [MlbTeam.Bal]: 'Bal',
  [MlbTeam.Bos]: 'Bos',
  [MlbTeam.LAA]: 'LAA',
  [MlbTeam.ChW]: 'ChW',
  [MlbTeam.Cle]: 'Cle',
  [MlbTeam.Det]: 'Det',
  [MlbTeam.KC]: 'KC',
  [MlbTeam.Mil]: 'Mil',
  [MlbTeam.Min]: 'Min',
  [MlbTeam.NYY]: 'NYY',
  [MlbTeam.Oak]: 'Oak',
  [MlbTeam.Sea]: 'Sea',
  [MlbTeam.Tex]: 'Tex',
  [MlbTeam.Tor]: 'Tor',
  [MlbTeam.Atl]: 'Atl',
  [MlbTeam.ChC]: 'ChC',
  [MlbTeam.Cin]: 'Cin',
  [MlbTeam.Hou]: 'Hou',
  [MlbTeam.LAD]: 'LAD',
  [MlbTeam.Wsh]: 'Wsh',
  [MlbTeam.NYM]: 'NYM',
  [MlbTeam.Phi]: 'Phi',
  [MlbTeam.Pit]: 'Pit',
  [MlbTeam.StL]: 'StL',
  [MlbTeam.SD]: 'SD',
  [MlbTeam.SF]: 'SF',
  [MlbTeam.Col]: 'Col',
  [MlbTeam.Mia]: 'Mia',
  [MlbTeam.Ari]: 'Ari',
  [MlbTeam.TB]: 'TB',
} as const;
