export interface MlbLineup {
    [key: number]: {
        abbrev: string;
        active: boolean;
        bench: boolean;
        canApplyLimitIndividually: boolean;
        display: boolean;
        displayOrder: number;
        eligiblePositions: number[];
        id: number;
        injuryRequired: boolean;
        lineupSlotEligible: boolean;
        name: string;
        parentId: number;
        starter: boolean;
    };
}

export const mlbLineupMap = {
    0: {
        abbrev: 'C',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 0,
        eligiblePositions: [2],
        id: 0,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Catcher',
        parentId: 12,
        starter: true,
    },
    1: {
        abbrev: '1B',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 1,
        eligiblePositions: [3],
        id: 1,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'First Base',
        parentId: 7,
        starter: true,
    },
    2: {
        abbrev: '2B',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 2,
        eligiblePositions: [4],
        id: 2,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Second Base',
        parentId: 6,
        starter: true,
    },
    3: {
        abbrev: '3B',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 3,
        eligiblePositions: [5],
        id: 3,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Third Base',
        parentId: 7,
        starter: true,
    },
    4: {
        abbrev: 'SS',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 4,
        eligiblePositions: [6],
        id: 4,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Shortstop',
        parentId: 6,
        starter: true,
    },
    5: {
        abbrev: 'OF',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 11,
        eligiblePositions: [7, 8, 9],
        id: 5,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Outfield',
        parentId: 12,
        starter: true,
    },
    6: {
        abbrev: '2B/SS',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 5,
        eligiblePositions: [4, 6],
        id: 6,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Middle Infielder',
        parentId: 12,
        starter: true,
    },
    7: {
        abbrev: '1B/3B',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 6,
        eligiblePositions: [3, 5],
        id: 7,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Corner Infielder',
        parentId: 12,
        starter: true,
    },
    8: {
        abbrev: 'LF',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 8,
        eligiblePositions: [7],
        id: 8,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Left Field',
        parentId: 5,
        starter: true,
    },
    9: {
        abbrev: 'CF',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 9,
        eligiblePositions: [8],
        id: 9,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Center Field',
        parentId: 5,
        starter: true,
    },
    10: {
        abbrev: 'RF',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 10,
        eligiblePositions: [9],
        id: 10,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Right Field',
        parentId: 5,
        starter: true,
    },
    11: {
        abbrev: 'DH',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 12,
        eligiblePositions: [10],
        id: 11,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Designated Hitter',
        parentId: 12,
        starter: true,
    },
    12: {
        abbrev: 'UTIL',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 13,
        eligiblePositions: [2, 3, 4, 5, 6, 7, 8, 9, 10],
        id: 12,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Utility',
        parentId: 21,
        starter: true,
    },
    13: {
        abbrev: 'P',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 14,
        eligiblePositions: [1, 11],
        id: 13,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Pitcher',
        parentId: 22,
        starter: true,
    },
    14: {
        abbrev: 'SP',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 15,
        eligiblePositions: [1],
        id: 14,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Starting Pitcher',
        parentId: 13,
        starter: true,
    },
    15: {
        abbrev: 'RP',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 16,
        eligiblePositions: [11],
        id: 15,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Relief Pitcher',
        parentId: 13,
        starter: true,
    },
    16: {
        abbrev: 'BE',
        active: false,
        bench: true,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 17,
        eligiblePositions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        id: 16,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Bench',
        parentId: 23,
        starter: false,
    },
    17: {
        abbrev: 'IL',
        active: false,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 18,
        eligiblePositions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        id: 17,
        injuryRequired: true,
        lineupSlotEligible: true,
        name: 'Injured List',
        parentId: 23,
        starter: false,
    },
    18: {
        abbrev: 'INV',
        active: false,
        bench: false,
        canApplyLimitIndividually: false,
        display: false,
        displayOrder: 19,
        eligiblePositions: [],
        id: 18,
        injuryRequired: false,
        lineupSlotEligible: false,
        name: 'Invalid Player',
        parentId: 23,
        starter: false,
    },
    19: {
        abbrev: 'IF',
        active: true,
        bench: false,
        canApplyLimitIndividually: false,
        display: true,
        displayOrder: 7,
        eligiblePositions: [3, 4, 5, 6],
        id: 19,
        injuryRequired: false,
        lineupSlotEligible: true,
        name: 'Infielder',
        parentId: 12,
        starter: true,
    },
    20: {
        abbrev: 'B',
        active: true,
        bench: false,
        canApplyLimitIndividually: true,
        display: true,
        displayOrder: 0,
        eligiblePositions: [2, 3, 4, 5, 6, 7, 8, 9, 10],
        id: 21,
        injuryRequired: false,
        lineupSlotEligible: false,
        name: 'Batters',
        parentId: 21,
        starter: false,
    },
    21: {
        abbrev: 'P',
        active: true,
        bench: false,
        canApplyLimitIndividually: true,
        display: true,
        displayOrder: 0,
        eligiblePositions: [1, 11],
        id: 22,
        injuryRequired: false,
        lineupSlotEligible: false,
        name: 'Pitchers',
        parentId: 22,
        starter: false,
    },
    22: {
        abbrev: 'MISC',
        active: true,
        bench: false,
        canApplyLimitIndividually: true,
        display: true,
        displayOrder: 0,
        id: 23,
        injuryRequired: false,
        lineupSlotEligible: false,
        name: 'Miscellaneous',
        parentId: 23,
        starter: false,
        eligiblePositions: []
    }
};
