import { RgTeam } from './team.model';

export const NBA_TEAM_MAP: Record<string, RgTeam> = {
  '125': {
    id: 125,
    xmlId: '583eccfa-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Atlantic',
    name: 'Boston Celtics',
    city: 'Boston',
    mascot: 'Celtics',
    hashtag: 'BOS',
    direction: 'N',
    timeZone: -4,
    stadium: 'TD Garden',
  },
  '126': {
    id: 126,
    xmlId: '583ec9d6-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Atlantic',
    name: 'Brooklyn Nets',
    city: 'Brooklyn',
    mascot: 'Nets',
    hashtag: 'BKN',
    direction: 'N',
    timeZone: -4,
    stadium: 'Barclays Center',
  },
  '127': {
    id: 127,
    xmlId: '583ec70e-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Atlantic',
    name: 'New York Knicks',
    city: 'New York',
    mascot: 'Knicks',
    hashtag: 'NYK',
    direction: 'N',
    timeZone: -4,
    stadium: 'Madison Square Garden',
  },
  '128': {
    id: 128,
    xmlId: '583ec87d-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Atlantic',
    name: 'Philadelphia 76ers',
    city: 'Philadelphia',
    mascot: '76ers',
    hashtag: 'PHI',
    direction: 'N',
    timeZone: -4,
    stadium: 'Wells Fargo Center',
  },
  '129': {
    id: 129,
    xmlId: '583ecda6-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Atlantic',
    name: 'Toronto Raptors',
    city: 'Toronto',
    mascot: 'Raptors',
    hashtag: 'TOR',
    direction: 'N',
    timeZone: -4,
    stadium: 'Air Canada Centre',
  },
  '130': {
    id: 130,
    xmlId: '583ec5fd-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Central',
    name: 'Chicago Bulls',
    city: 'Chicago',
    mascot: 'Bulls',
    hashtag: 'CHI',
    direction: 'N',
    timeZone: -5,
    stadium: 'United Center',
  },
  '131': {
    id: 131,
    xmlId: '583ec773-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Central',
    name: 'Cleveland Cavaliers',
    city: 'Cleveland',
    mascot: 'Cavaliers',
    hashtag: 'CLE',
    direction: 'N',
    timeZone: -4,
    stadium: 'Quicken Loans Arena',
  },
  '132': {
    id: 132,
    xmlId: '583ec928-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Central',
    name: 'Detroit Pistons',
    city: 'Detroit',
    mascot: 'Pistons',
    hashtag: 'DET',
    direction: 'N',
    timeZone: -4,
    stadium: 'The Palace of Auburn Hills',
  },
  '133': {
    id: 133,
    xmlId: '583ec7cd-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Central',
    name: 'Indiana Pacers',
    city: 'Indiana',
    mascot: 'Pacers',
    hashtag: 'IND',
    direction: 'N',
    timeZone: -4,
    stadium: 'Bankers Life Fieldhouse',
  },
  '134': {
    id: 134,
    xmlId: '583ecefd-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Central',
    name: 'Milwaukee Bucks',
    city: 'Milwaukee',
    mascot: 'Bucks',
    hashtag: 'MIL',
    direction: 'N',
    timeZone: -5,
    stadium: 'BMO Harris Bradley Center',
  },
  '135': {
    id: 135,
    xmlId: '583ecb8f-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Southeast',
    name: 'Atlanta Hawks',
    city: 'Atlanta',
    mascot: 'Hawks',
    hashtag: 'ATL',
    direction: 'N',
    timeZone: -4,
    stadium: 'Philips Arena',
  },
  '136': {
    id: 136,
    xmlId: '583ec97e-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Southeast',
    name: 'Charlotte Hornets',
    city: 'Charlotte',
    mascot: 'Hornets',
    hashtag: 'CHA',
    direction: 'N',
    timeZone: -4,
    stadium: 'Time Warner Cable Arena',
  },
  '137': {
    id: 137,
    xmlId: '583ecea6-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Southeast',
    name: 'Miami Heat',
    city: 'Miami',
    mascot: 'Heat',
    hashtag: 'MIA',
    direction: 'N',
    timeZone: -4,
    stadium: 'American Airlines Arena',
  },
  '138': {
    id: 138,
    xmlId: '583ed157-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Southeast',
    name: 'Orlando Magic',
    city: 'Orlando',
    mascot: 'Magic',
    hashtag: 'ORL',
    direction: 'N',
    timeZone: -4,
    stadium: 'Amway Center',
  },
  '139': {
    id: 139,
    xmlId: '583ec8d4-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'EC',
    subdivision: 'Southeast',
    name: 'Washington Wizards',
    city: 'Washington',
    mascot: 'Wizards',
    hashtag: 'WAS',
    direction: 'N',
    timeZone: -4,
    stadium: 'Verizon Center',
  },
  '140': {
    id: 140,
    xmlId: '583ecf50-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Southwest',
    name: 'Dallas Mavericks',
    city: 'Dallas',
    mascot: 'Mavericks',
    hashtag: 'DAL',
    direction: 'N',
    timeZone: -5,
    stadium: 'American Airlines Center',
  },
  '141': {
    id: 141,
    xmlId: '583ecb3a-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Southwest',
    name: 'Houston Rockets',
    city: 'Houston',
    mascot: 'Rockets',
    hashtag: 'HOU',
    direction: 'N',
    timeZone: -5,
    stadium: 'Toyota Center',
  },
  '142': {
    id: 142,
    xmlId: '583eca88-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Southwest',
    name: 'Memphis Grizzlies',
    city: 'Memphis',
    mascot: 'Grizzlies',
    hashtag: 'MEM',
    direction: 'N',
    timeZone: -5,
    stadium: 'FedExForum',
  },
  '143': {
    id: 143,
    xmlId: '583ecc9a-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Southwest',
    name: 'New Orleans Pelicans',
    city: 'New Orleans',
    mascot: 'Pelicans',
    hashtag: 'NOP',
    direction: 'N',
    timeZone: -5,
    stadium: 'Smoothie King Center',
  },
  '144': {
    id: 144,
    xmlId: '583ecd4f-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Southwest',
    name: 'San Antonio Spurs',
    city: 'San Antonio',
    mascot: 'Spurs',
    hashtag: 'SAS',
    direction: 'N',
    timeZone: -5,
    stadium: 'AT&T Center',
  },
  '145': {
    id: 145,
    xmlId: '583ed102-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Northwest',
    name: 'Denver Nuggets',
    city: 'Denver',
    mascot: 'Nuggets',
    hashtag: 'DEN',
    direction: 'N',
    timeZone: -6,
    stadium: 'Pepsi Center',
  },
  '146': {
    id: 146,
    xmlId: '583eca2f-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Northwest',
    name: 'Minnesota Timberwolves',
    city: 'Minnesota',
    mascot: 'Timberwolves',
    hashtag: 'MIN',
    direction: 'N',
    timeZone: -5,
    stadium: 'Target Center',
  },
  '147': {
    id: 147,
    xmlId: '583ed056-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Northwest',
    name: 'Portland Trail Blazers',
    city: 'Portland',
    mascot: 'Trail Blazers',
    hashtag: 'POR',
    direction: 'N',
    timeZone: -7,
    stadium: 'Moda Center',
  },
  '148': {
    id: 148,
    xmlId: '583ecfff-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Northwest',
    name: 'Oklahoma City Thunder',
    city: 'Oklahoma City',
    mascot: 'Thunder',
    hashtag: 'OKC',
    direction: 'N',
    timeZone: -5,
    stadium: 'Chesapeake Energy Arena',
  },
  '149': {
    id: 149,
    xmlId: '583ece50-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Northwest',
    name: 'Utah Jazz',
    city: 'Utah',
    mascot: 'Jazz',
    hashtag: 'UTA',
    direction: 'N',
    timeZone: -6,
    stadium: 'EnergySolutions Arena',
  },
  '150': {
    id: 150,
    xmlId: '583ec825-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Pacific',
    name: 'Golden State Warriors',
    city: 'Golden State',
    mascot: 'Warriors',
    hashtag: 'GSW',
    direction: 'N',
    timeZone: -7,
    stadium: 'Oracle Arena',
  },
  '151': {
    id: 151,
    xmlId: '583ecdfb-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Pacific',
    name: 'LA Clippers',
    city: 'Los Angeles',
    mascot: 'Clippers',
    hashtag: 'LAC',
    direction: 'N',
    timeZone: -7,
    stadium: 'Staples Center',
  },
  '152': {
    id: 152,
    xmlId: '583ecae2-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Pacific',
    name: 'Los Angeles Lakers',
    city: 'Los Angeles',
    mascot: 'Lakers',
    hashtag: 'LAL',
    direction: 'N',
    timeZone: -7,
    stadium: 'Staples Center',
  },
  '153': {
    id: 153,
    xmlId: '583ecfa8-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Pacific',
    name: 'Phoenix Suns',
    city: 'Phoenix',
    mascot: 'Suns',
    hashtag: 'PHO',
    direction: 'N',
    timeZone: -6,
    stadium: 'Talking Stick Resort Arena',
  },
  '154': {
    id: 154,
    xmlId: '583ed0ac-fb46-11e1-82cb-f4ce4684ea4c',
    sportId: 3,
    division: 'WC',
    subdivision: 'Pacific',
    name: 'Sacramento Kings',
    city: 'Sacramento',
    mascot: 'Kings',
    hashtag: 'SAC',
    direction: 'N',
    timeZone: -7,
    stadium: 'Sleep Train Arena',
  },
} as const;

export const enum RgTeamId {
  BOS = 125,
  BKN,
  NYK,
  PHI,
  TOR,
  CHI,
  CLE,
  DET,
  IND,
  MIL,
  ATL,
  CHA,
  MIA,
  ORL,
  WAS,
  DAL,
  HOU,
  MEM,
  NOP,
  SAS,
  DEN,
  MIN,
  POR,
  OKC,
  UTA,
  GSW,
  LAC,
  LAL,
  PHO,
  SAC,
}

export const NBA_RG_TEAM_ID_MAP: Record<string, string> = {
  '125': 'BOS',
  '126': 'BKN',
  '127': 'NYK',
  '128': 'PHI',
  '129': 'TOR',
  '130': 'CHI',
  '131': 'CLE',
  '132': 'DET',
  '133': 'IND',
  '134': 'MIL',
  '135': 'ATL',
  '136': 'CHA',
  '137': 'MIA',
  '138': 'ORL',
  '139': 'WAS',
  '140': 'DAL',
  '141': 'HOU',
  '142': 'MEM',
  '143': 'NOP',
  '144': 'SAS',
  '145': 'DEN',
  '146': 'MIN',
  '147': 'POR',
  '148': 'OKC',
  '149': 'UTA',
  '150': 'GSW',
  '151': 'LAC',
  '152': 'LAL',
  '153': 'PHO',
  '154': 'SAC',
} as const;
